# Generated by Django 5.2.5 on 2025-08-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
    ]
