# Generated by Django 5.2.5 on 2025-09-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('kitchen', 'キッチン'), ('hall', 'ホール')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_activities', to='employees.attendance')),
            ],
        ),
    ]
